= Gradle Play Plugin image:https://travis-ci.org/gradle/playframework.svg?branch=master["Build Status", link="https://travis-ci.org/gradle/playframework"]

== Documentation 

- https://gradle.github.io/playframework/[User manual]
- https://github.com/gradle/playframework/tree/master/src/docs/samples[Samples]

== Development

=== Minimum requirements

To engage in the development of the plugin, follow the minimum requirements shown in the table below.

[options="header"]
|==========================
|Tool    |Minimum Version
|JDK     |Oracle JDK or OpenJDK 8.x, anything higher won't work with Scala 2.11
|Gradle  |5.0 or higher
|IDE     |IntelliJ 2018.2 or higher
|==========================

=== Executing the build

The plugin follows the standard conventions of a Java project modeled with Gradle. Furthermore, the project defines a task for running integration tests. To compile the code, execute all tests and build the plugin's artifact, run the following command.

**Linux & MacOSX**

----
./gradlew build
----

**Windows**

----
gradlew.bat build
----

=== Working in the IDE

Importing the project into IntelliJ is straight forward. From the menu select _File > Open... > Open as Project_ and point it to the `build.gradle.kts` file. In the following pop-up window, ensure that the default Gradle Wrapper is selected and "Create separate module per source set" is checked.

== Release

The project currently doesn't define a release process that can be triggered by running a single task. Following the process below.

1. Build the binary artifact and publish it to the Gradle Plugin Portal by running the task `publishPlugins`.
2. Build and publish the Javadocs and the user guide by running the task `gitPublishPush`.
3. Manually update the plugin version for all samples in the directory `src/docs/samples`. Commit and push the changes to GitHub.

The following paragraphs explain some of the steps in more detail.

=== Generating documentation

The markup language for the user guide of this plugin is AsciiDoc. Documentation sources sit in the directory `src/docs`. To generate the HTML version of the plugin user guide, run the task `asciidoctor`. The generated HTML will be available in the directory `build/asciidoc/html5`.

=== Publishing documentation to GitHub Pages

Documentation (user guide & Javadocs) is hosted on https://pages.github.com/[GitHub Pages]. To publish the documentation to GitHub Pages, execute the task `gitPublishPush`. Make sure to provide the required GitHub token by passing the system property `-Dorg.ajoberstar.grgit.auth.username=$GH_TOKEN`.

