[[migrating-from-standard-play-plugin]]
== Migrating from Gradle's standard Play plugin

The following features are not available in this plugin:

* Any features of the https://blog.gradle.org/state-and-future-of-the-gradle-software-model[Gradle software model] and its plugin ecosystem.
* The custom configurations `playTest` and `playRun` do not exist anymore. Use the standard configurations `implementation`, `testImplementation` and `runtime` of the Java/Scala plugin instead.
* The extension does not allow for configuring a target platform. You will need to configure Play, Scala and Java version individually.
* {uri-gradle-userguide}//play_plugin.html#sec:adding_extra_source_sets[Adding new source sets] of a specific type is a built-in feature of the software model. This functionality is currently not available.
* The concept of an "asset" does not exist and therefore cannot be used to {uri-gradle-userguide}/play_plugin.html#sec:injecting_a_custom_asset_pipeline[configure a custom asset pipeline].
* Source sets cannot be added by type. You will need to add additional source directories to the existing source sets provided by the plugin.
* The CoffeeScript plugin is not available anymore.